---
title: "HW3RMD"
author: "Noah Williams"
date: "2024-12-04"
output: html_document
---
Cobbled together through the power of prayer, dumb luck these and like 3 chatgpt clones to spellcheck the error mesages
https://stackoverflow.com/questions/57491589/ignore-all-errors-occurring-when-knitting-r-markdown-rmd-file
https://devtools.r-lib.org/
```{r}
require("devtools")
require("roxygen2")
require("usethis")
require("testthat")
require("readr")
require("datap")
require("tidyverse")
require("readxl")
require("assertthat")
require("Rd2md")
```

```{r}

# Load the package
load_all()

# Load data
observed_data <- read_csv("contraceptive_use.csv") %>%
  filter(is_in_union == "Y") %>%
  mutate(
    year = (start_date + end_date) / 2,
    cp = contraceptive_use_modern * 100
  ) %>%
  select(division_numeric_code, year, cp)

# Example dataset `est` with model estimates
est <- read_csv("est.csv")

get_width_ci(est, iso_code = 4, coverage = 95)
 


.get_width_ci(est, iso_code = 4, coverage = 80)
```

```{r}

document()
Rd2markdown(
  rdfile = "C:/Users/Toyb/Downloads/HW2/myutils/man/plot_cp.Rd",
  outfile = "C:/Users/Toyb/Downloads/HW2/myutils/plot_cp.md"
)
```
```{r, echo=FALSE, results='asis'}
cat(readLines("plot_cp.md"), sep = "\n")
```


Question 2 errors


```{r, error=TRUE}

 
# Input dat does NOT contain variable iso, year and/or cp
plot_cp(est, observed_data %>% select(-iso), iso_code = 4)
plot_cp(est, observed_data %>% select(-year), iso_code = 4)
plot_cp(est, observed_data %>% select(-cp), iso_code = 4)

# iso_code is not found in “dat” or “est”
plot_cp(est %>% select(-iso), observed_data, iso_code = 4)
plot_cp(est, observed_data %>% select(-iso), iso_code = 4)



```

Question 3
https://github.com/Nwillia/HW2
It links to HW3
